import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import NavBar from "@/components/ui/NavBar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "BD Custom Timber Works",
  description: "Generated by create next app",
  openGraph: {
    title: "BD Custom Timber Works",
    description: "Generated by create next app",
    url: "https://bdcustomtimberworks.com",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        style={{
          height: "100vh",
          margin: "0",
          display: "flex",
          flexDirection: "column",
        }}
      >
        <Provider>
          <NavBar />
          <main style={{ flex: 1, overflowY: "auto" }}>{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
